services:
  - type: web
    name: dapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DB_PATH
        value: /var/data/database.db
    disk:
      name: dapi-db-data
      mountPath: /var/data
      sizeGB: 1
